### ISSUE TITLE
Please update/upgrade to the latest nativescript. Demo is not working.

### ISSUE THREAD

**Issue by sylwesterdigital** [triniwiz/nativescript-ffmpeg#9]
```
➜  demo git:(master) uname -a
Darwin Aerosol.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
```
```
➜  demo git:(master) tns doctor
You are using the deprecated nsconfig.json file. Just be aware that NativeScript 7 has an improved nativescript.config.(js|ts) file for when you're ready to upgrade this project.
✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 12.2.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 7.1.1 and the latest available version is 7.1.2.
⚠ Update available for component tns-core-modules. Your current version is 5.4.3 and the latest available version is 6.5.24.
⚠ Update available for component tns-ios. Your current version is 5.2.0 and the latest available version is 6.5.4.
⚠ Update available for component tns-android. Your current version is 5.2.1 and the latest available version is 6.5.3.
```

```
➜  demo git:(master) npm i
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.0.4: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

> fsevents@1.2.13 install /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> core-js@2.6.12 postinstall /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> nativescript-dev-typescript@0.8.0 postinstall /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo/node_modules/nativescript-dev-typescript
> node postinstall.js

Adding 'es6' lib to tsconfig.json...
Adding 'dom' lib to tsconfig.json...
Adding tns-core-modules path mappings lib to tsconfig.json...

> nativescript-dev-webpack@0.20.3 postinstall /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo/node_modules/nativescript-dev-webpack
> node postinstall.js

Creating file: /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo/webpack.config.js

NativeScript Webpack plugin was successfully added.
You can now bundle your project by passing --bundle flag to NativeScript CLI commands:
    - tns build android --bundle
    - tns build ios --bundle
    - tns run android --bundle
    - tns run ios --bundle
You can also pass the "--env.uglify" flag to use UglifyJS for minification.
For more information check out https://docs.nativescript.org/tooling/bundling-with-webpack#bundling.


> nativescript-ffmpeg-plugin@0.0.2 postinstall /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo/node_modules/nativescript-ffmpeg-plugin
> node postinstall-hooks.js

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'nativescript-hook'
Require stack:
- /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/postinstall-hooks.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/misiak/Desktop/2021/nativescript-ffmpeg/src/postinstall-hooks.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/misiak/Desktop/2021/nativescript-ffmpeg/src/postinstall-hooks.js'
  ]
}
npm WARN rollback Rolling back big.js@5.2.2 failed (this is probably harmless): /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/node_modules/big.js is not a child of /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo
npm WARN rollback Rolling back co@4.6.0 failed (this is probably harmless): /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/node_modules/co is not a child of /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo
npm WARN rollback Rolling back emojis-list@3.0.0 failed (this is probably harmless): /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/node_modules/emojis-list is not a child of /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo
npm WARN rollback Rolling back fast-deep-equal@1.1.0 failed (this is probably harmless): /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/node_modules/fast-deep-equal is not a child of /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo
npm WARN rollback Rolling back fast-json-stable-stringify@2.1.0 failed (this is probably harmless): /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/node_modules/fast-json-stable-stringify is not a child of /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo
npm WARN rollback Rolling back json-schema-traverse@0.3.1 failed (this is probably harmless): /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/node_modules/json-schema-traverse is not a child of /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo
npm WARN rollback Rolling back ajv@5.5.2 failed (this is probably harmless): /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/node_modules/ajv is not a child of /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo
npm WARN rollback Rolling back minimist@1.2.5 failed (this is probably harmless): /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/node_modules/minimist is not a child of /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo
npm WARN rollback Rolling back json5@1.0.1 failed (this is probably harmless): /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/node_modules/json5 is not a child of /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo
npm WARN rollback Rolling back loader-utils@1.4.0 failed (this is probably harmless): /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/node_modules/loader-utils is not a child of /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo
npm WARN rollback Rolling back schema-utils@0.3.0 failed (this is probably harmless): /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/node_modules/schema-utils is not a child of /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo
npm WARN rollback Rolling back nativescript-worker-loader@0.9.5 failed (this is probably harmless): /Users/misiak/Desktop/2021/nativescript-ffmpeg/src/node_modules/nativescript-worker-loader is not a child of /Users/misiak/Desktop/2021/nativescript-ffmpeg/demo
npm WARN notsup Unsupported engine for karma@1.7.1: wanted: {"node":"0.10 || 0.12 || 4 || 5 || 6 || 7 || 8"} (current: {"node":"12.16.1","npm":"6.14.11"})
npm WARN notsup Not compatible with your version of node/npm: karma@1.7.1
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN demo No description
npm WARN demo No repository field.
npm WARN demo No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-ffmpeg-plugin@0.0.2 postinstall: `node postinstall-hooks.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nativescript-ffmpeg-plugin@0.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/misiak/.npm/_logs/2021-01-21T18_23_23_171Z-debug.log
```

**Comment by imperatormk** [comment]
@triniwiz please?

**Comment by triniwiz** [comment]
Located [here](https://github.com/triniwiz/nativescript-plugins)
